language: cpp

install: 
  - chmod +x ./build/CI/travis-ci/install.sh
  - ./build/CI/travis-ci/install.sh

script:
  - chmod +x ./build/CI/travis-ci/run.sh
  - ./build/CI/travis-ci/run.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
      - llvm-toolchain-trusty-4.0
    packages:
      - clang-4.0
      - g++-6

compiler:
  - gcc-6
  - clang-4.0

env:
  - TARGET="unit-deque unit-misc unit-pqueue"   BUILD_TYPE=Release
  - TARGET="unit-queue unit-stack"              BUILD_TYPE=Release
  - TARGET=unit-ilist                           BUILD_TYPE=Release
  - TARGET=unit-list                            BUILD_TYPE=Release
# - TARGET=unit-iset                            BUILD_TYPE=Release
  - TARGET=unit-iset-feldman                    BUILD_TYPE=Release
  - TARGET=unit-iset-michael                    BUILD_TYPE=Release
  - TARGET=unit-iset-skip                       BUILD_TYPE=Release
  - TARGET=unit-iset-split                      BUILD_TYPE=Release
# - TARGET=unit-set                             BUILD_TYPE=Release
  - TARGET=unit-set-feldman                     BUILD_TYPE=Release
  - TARGET=unit-set-michael                     BUILD_TYPE=Release
  - TARGET=unit-set-skip                        BUILD_TYPE=Release
  - TARGET=unit-set-split                       BUILD_TYPE=Release
  - TARGET=unit-striped-set                     BUILD_TYPE=Release
# - TARGET=unit-map                             BUILD_TYPE=Release
  - TARGET=unit-map-feldman                     BUILD_TYPE=Release
  - TARGET=unit-map-michael                     BUILD_TYPE=Release
  - TARGET=unit-map-skip                        BUILD_TYPE=Release
  - TARGET=unit-map-split                       BUILD_TYPE=Release
  - TARGET=unit-striped-map                     BUILD_TYPE=Release
  - TARGET=unit-tree                            BUILD_TYPE=Release
  - TARGET="unit-deque unit-misc unit-pqueue"   BUILD_TYPE=Debug
  - TARGET="unit-queue unit-stack"              BUILD_TYPE=Debug
  - TARGET=unit-ilist                           BUILD_TYPE=Debug
  - TARGET=unit-list                            BUILD_TYPE=Debug
# - TARGET=unit-iset                            BUILD_TYPE=Debug
  - TARGET=unit-iset-feldman                    BUILD_TYPE=Debug
  - TARGET=unit-iset-michael                    BUILD_TYPE=Debug
  - TARGET=unit-iset-skip                       BUILD_TYPE=Debug
  - TARGET=unit-iset-split                      BUILD_TYPE=Debug
# - TARGET=unit-set                             BUILD_TYPE=Debug
  - TARGET=unit-set-feldman                     BUILD_TYPE=Debug
  - TARGET=unit-set-michael                     BUILD_TYPE=Debug
  - TARGET=unit-set-skip                        BUILD_TYPE=Debug
  - TARGET=unit-set-split                       BUILD_TYPE=Debug
  - TARGET=unit-striped-set                     BUILD_TYPE=Debug
# - TARGET=unit-map                             BUILD_TYPE=Debug
  - TARGET=unit-map-feldman                     BUILD_TYPE=Debug
  - TARGET=unit-map-michael                     BUILD_TYPE=Debug
  - TARGET=unit-map-skip                        BUILD_TYPE=Debug
  - TARGET=unit-map-split                       BUILD_TYPE=Debug
  - TARGET=unit-striped-map                     BUILD_TYPE=Debug
  - TARGET=unit-tree                            BUILD_TYPE=Debug


#matrix:
#  include:
#    - os: osx
#      osx_image: xcode8
#      env: BUILD_TYPE=Debug
#    - os: osx
#      osx_image: xcode8.2
#      env: BUILD_TYPE=Debug
#    - os: osx
#      osx_image: xcode8
#      env: BUILD_TYPE=Release
#    - os: osx
#      osx_image: xcode8.2
#      env: BUILD_TYPE=Release
