
language: cpp
compiler: g++
#  - gcc
#  - clang

before_install:
    - export LIBCDS_BUILD_DIR=`pwd`
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - export BOOST_VERSION="57"
    - wget -O boost_1_${BOOST_VERSION}_0.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.${BOOST_VERSION}.0/boost_1_${BOOST_VERSION}_0.tar.bz2/download
    - tar xjf boost_1_${BOOST_VERSION}_0.tar.bz2
    - cd boost_1_${BOOST_VERSION}_0
    - ./bootstrap.sh
    - ./b2 --with-thread --with-atomic --with-date_time --with-system --with-timer --stagedir=stage64 --toolset=gcc address-model=64
    - cd ..

before_script: cd ./build

script: ./build.sh -b 64 -j 4 -x ${CXX} -z '-Wall -Wextra -pedantic' --with-boost ../boost_1_${BOOST_VERSION}_0 -t test_hdr

#after_success:

#after_failure:

after_script: cd ..

# blacklist
branches:
  except:
    - integration

# whitelist
branches:
  only:
    - master
    - dev
