language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - g++-6
      - clang-4.0

install:
  - ./build/CI/travis-ci/install.sh

script:
  - ./build/CI/travis-ci/run.sh

#compiler:
#  - g++-6
#  - clang-4.0

env:
  - TARGET="unit-deque unit-misc unit-pqueue"   BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET="unit-queue unit-stack"              BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-ilist                           BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-list                            BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
# - TARGET=unit-iset                            BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-iset-feldman                    BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-iset-michael                    BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-iset-skip                       BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-iset-split                      BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
# - TARGET=unit-set                             BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-set-feldman                     BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-set-michael                     BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-set-skip                        BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-set-split                       BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-striped-set                     BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
# - TARGET=unit-map                             BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-map-feldman                     BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-map-michael                     BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-map-skip                        BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-map-split                       BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-striped-map                     BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET=unit-tree                            BUILD_TYPE=Release CXX=g++-6 CC=gcc-6
  - TARGET="unit-deque unit-misc unit-pqueue"   BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET="unit-queue unit-stack"              BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-ilist                           BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-list                            BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
# - TARGET=unit-iset                            BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-iset-feldman                    BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-iset-michael                    BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-iset-skip                       BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-iset-split                      BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
# - TARGET=unit-set                             BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-set-feldman                     BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-set-michael                     BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-set-skip                        BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-set-split                       BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-striped-set                     BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
# - TARGET=unit-map                             BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-map-feldman                     BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-map-michael                     BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-map-skip                        BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-map-split                       BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-striped-map                     BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6
  - TARGET=unit-tree                            BUILD_TYPE=Debug CXX=g++-6 CC=gcc-6

  - TARGET="unit-deque unit-misc unit-pqueue"   BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET="unit-queue unit-stack"              BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-ilist                           BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-list                            BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
# - TARGET=unit-iset                            BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-iset-feldman                    BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-iset-michael                    BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-iset-skip                       BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-iset-split                      BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
# - TARGET=unit-set                             BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-set-feldman                     BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-set-michael                     BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-set-skip                        BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-set-split                       BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-striped-set                     BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
# - TARGET=unit-map                             BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-map-feldman                     BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-map-michael                     BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-map-skip                        BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-map-split                       BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-striped-map                     BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-tree                            BUILD_TYPE=Release CXX=clang-4.0 CC=clang-4.0
  - TARGET="unit-deque unit-misc unit-pqueue"   BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET="unit-queue unit-stack"              BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-ilist                           BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-list                            BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
# - TARGET=unit-iset                            BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-iset-feldman                    BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-iset-michael                    BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-iset-skip                       BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-iset-split                      BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
# - TARGET=unit-set                             BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-set-feldman                     BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-set-michael                     BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-set-skip                        BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-set-split                       BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-striped-set                     BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
# - TARGET=unit-map                             BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-map-feldman                     BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-map-michael                     BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-map-skip                        BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-map-split                       BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-striped-map                     BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0
  - TARGET=unit-tree                            BUILD_TYPE=Debug CXX=clang-4.0 CC=clang-4.0

#matrix:
#  include:
#    - os: osx
#      osx_image: xcode8
#      env: BUILD_TYPE=Debug
#    - os: osx
#      osx_image: xcode8.2
#      env: BUILD_TYPE=Debug
#    - os: osx
#      osx_image: xcode8
#      env: BUILD_TYPE=Release
#    - os: osx
#      osx_image: xcode8.2
#      env: BUILD_TYPE=Release
